openapi: 3.0.3
info:
  title: Soccer Notebook API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api

paths:
  /users:
    post:
      summary: ユーザー登録
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateRequest'
      responses:
        '201':
          description: ユーザー作成成功
    get:
      summary: ユーザー一覧取得
      responses:
        '200':
          description: ユーザー一覧
  /users/{userId}:
    get:
      summary: ユーザー詳細取得
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ユーザー情報
    put:
      summary: ユーザー情報更新
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdateRequest'
      responses:
        '200':
          description: ユーザー更新成功
    delete:
      summary: ユーザー削除
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: ユーザー削除成功
  /login:
    post:
      summary: ログイン
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: ログイン成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: 認証失敗
  /logout:
    post:
      summary: ログアウト
      responses:
        '200':
          description: ログアウト成功
  /notes:
    post:
      summary: サッカーノート登録
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteCreateRequest'
      responses:
        '201':
          description: ノート作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note' # 登録成功時は作成されたノートを返す想定
    get:
      summary: サッカーノート一覧取得
      parameters:
        - in: query
          name: date
          schema:
            type: string
            format: date
          description: 絞り込む日付
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: ページ番号
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            default: 30
            enum: [10, 30, 50]
          description: 1ページあたりの件数
      responses:
        '200':
          description: ノート一覧（ページネーション情報含む想定）
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalCount:
                    type: integer
                    description: 全件数
                  page:
                    type: integer
                    description: 現在のページ番号
                  limit:
                    type: integer
                    description: 1ページあたりの件数
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/NoteSummary' # 一覧表示用の簡易スキーマを想定
  /notes/{noteId}:
    get:
      summary: サッカーノート詳細取得
      parameters:
        - in: path
          name: noteId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ノート情報
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note' # 詳細取得時は完全なスキーマを返す想定
    put:
      summary: サッカーノート更新
      parameters:
        - in: path
          name: noteId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteUpdateRequest'
      responses:
        '200':
          description: ノート更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note' # 更新成功時は更新されたノートを返す想定
    delete:
      summary: サッカーノート削除
      parameters:
        - in: path
          name: noteId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: ノート削除成功

components:
  schemas:
    # 各ファイルからスキーマ定義をインクルード
    $ref: './user.yaml#/components/schemas'
    $ref: './auth.yaml#/components/schemas'
    $ref: './note.yaml#/components/schemas'
  # 必要であれば他のcomponentsも分割・参照可能 